Name = "ugwinst0"
Host = "0.0.0.0"
Port = 8080
Protocol = "http"
LogLevel = "info"
Loggers = ["app", "tx", "detail"]
LogDir = "log/ugwinst0"
WorkingDir = "./"
MaxConnections = 100

[[OutBound]]
Name = "ob0"
Host = "192.168.56.103"
Protocol = "tcp"
Port = 8080

[[OutBound]]
Name = "ob1"
Host = "192.168.56.104"
Protocol = "tcp"
Port = 8081